language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - py.test --cov=./ --cov-config=.coveragerc

after_success:
  - coveralls
